In [2]:
import cv2
import numpy as np

np.uint8

numpy.uint8

In [5]:
# ---① 연산에 사용할 배열 생성
a = np.uint8([[200, 50]]) 
b = np.uint8([[100, 100]])

In [6]:
#---② NumPy 배열 직접 연산 - 사칙연산 
add1 = a + b
sub1 = a - b
mult1 = a * 2
div1 = a / 3

In [7]:
# ---③ OpenCV API를 이용한 연산
add2 = cv2.add(a, b)
sub2 = cv2.subtract(a, b)
mult2 = cv2.multiply(a , 2)
div2 = cv2.divide(a, 3)

In [8]:
#---④ 각 연산 결과 출력
print(add1, add2)
print(sub1, sub2)
print(mult1, mult2)
print(div1, div2)

[[ 44 150]] [[255 150]]
[[100 206]] [[100   0]]
[[144 100]] [[255 100]]
[[66.66666667 16.66666667]] [[67 17]]


In [9]:
import cv2
import numpy as np

# ---① 연산에 사용할 배열 생성
# 두 개의 8비트 unsigned int 타입의 2차원 배열 생성
a = np.uint8([[200, 50]]) 
b = np.uint8([[100, 100]])

#---② NumPy 배열 직접 연산
# NumPy를 이용한 배열 간의 직접 연산
add1 = a + b  # 배열 a와 b를 더함
sub1 = a - b  # 배열 a에서 b를 뺌
mult1 = a * 2  # 배열 a에 2를 곱함
div1 = a / 3  # 배열 a를 3으로 나눔

# ---③ OpenCV API를 이용한 연산
# OpenCV의 함수를 이용한 배열 연산
add2 = cv2.add(a, b)  # OpenCV add 함수를 이용해 배열 a와 b를 더함
sub2 = cv2.subtract(a, b)  # OpenCV subtract 함수를 이용해 배열 a에서 b를 뺌
mult2 = cv2.multiply(a , 2)  # OpenCV multiply 함수를 이용해 배열 a에 2를 곱함
div2 = cv2.divide(a, 3)  # OpenCV divide 함수를 이용해 배열 a를 3으로 나눔

#---④ 각 연산 결과 출력
# NumPy와 OpenCV 함수의 연산 결과를 출력
print(add1, add2)
print(sub1, sub2)
print(mult1, mult2)
print(div1, div2)


[[ 44 150]] [[255 150]]
[[100 206]] [[100   0]]
[[144 100]] [[255 100]]
[[66.66666667 16.66666667]] [[67 17]]
