In [18]:
import numpy as np
import cv2

def labeling_basic():
    # 8x8 배열을 생성하고 이진 이미지로 변환
    src = np.array([[0, 0, 1, 1, 0, 0, 0, 0],
                    [1, 1, 1, 1, 0, 0, 1, 0],
                    [1, 1, 1, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 1, 0],
                    [0, 0, 0, 1, 1, 1, 1, 0],
                    [0, 0, 0, 1, 0, 0, 1, 0],
                    [0, 0, 1, 1, 1, 1, 1, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0]]).astype(np.uint8)

    # 이진 이미지로 변환 (값이 0이면 0, 1이면 255로 변환)
    src = src * 255

    # 연결된 구성 요소를 찾음
    cnt, labels = cv2.connectedComponents(src)

    # 결과 출력
    print('src:')
    print(src)
    print('labels:')
    print(labels)
    print('number of labels:', cnt)

def labeling_stats():
    # 이미지를 그레이스케일로 읽어옴
    src = cv2.imread('C:/ex/py/cv/img/kb2.jpg', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    # 이진화: Otsu의 방법을 사용하여 이진 이미지 생성
    _, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

    # 연결된 구성 요소 및 통계 정보를 얻음
    cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)

    # 원본 이미지를 BGR로 변환
    dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

    # 각 구성 요소의 통계 정보를 사용하여 사각형을 그림
    for i in range(1, cnt):
        (x, y, w, h, area) = stats[i]

        # 면적이 20 미만인 경우 무시
        if area < 20:
            continue

        pt1 = (x, y)
        pt2 = (x + w, y + h)
        cv2.rectangle(dst, pt1, pt2, (0, 255, 255))  # 사각형을 그려서 표시

    # cv2 이미지 파일로 저장
    cv2.imwrite('C:/Users/winrr/Pictures/Screenshots/pfile/labeling.jpg',dst) 

    # 결과 이미지 표시
    cv2.imshow('src', src)
    cv2.imshow('dst', dst)

    cv2.waitKey()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    labeling_basic()  # 기본 레이블링 함수 호출
    labeling_stats()  # 통계 기반 레이블링 함수 호출


src:
[[  0   0 255 255   0   0   0   0]
 [255 255 255 255   0   0 255   0]
 [255 255 255 255   0   0   0   0]
 [  0   0   0   0   0 255 255   0]
 [  0   0   0 255 255 255 255   0]
 [  0   0   0 255   0   0 255   0]
 [  0   0 255 255 255 255 255   0]
 [  0   0   0   0   0   0   0   0]]
labels:
[[0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 2 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 0 3 3 0]
 [0 0 0 3 3 3 3 0]
 [0 0 0 3 0 0 3 0]
 [0 0 3 3 3 3 3 0]
 [0 0 0 0 0 0 0 0]]
number of labels: 4
